---

- hosts: galaxyservers
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['python-psycopg2', 'git', 'python-virtualenv', 'make']
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  roles:
    - galaxyproject.repos
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - galaxyproject.galaxy
    - geerlingguy.pip
    - usegalaxy-eu.supervisor
    - geerlingguy.nginx
    - galaxyproject.proftpd
