---

- hosts: galaxyservers
  roles:
    - geerlingguy.nginx
    - galaxyproject.proftpd
    - usegalaxy-eu.certbot
  vars:
    # these are set by the galaxy role and needed by other vars
    galaxy_mutable_data_dir: /srv/galaxy/var
    galaxy_server_dir: /srv/galaxy/server
    galaxy_venv_dir: /srv/galaxy/venv
    # override the end-of-day versions of these variables just for this playbook
    certbot_environment: staging
