---

- hosts: galaxyservers
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['python-psycopg2', 'git', 'python-virtualenv', 'make']
  handlers:
    - name: Restart Galaxy
      supervisorctl:
        name: galaxy
        state: restarted
  roles:
    - galaxyproject.repos
    - galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - galaxyproject.cvmfs
    - galaxyproject.galaxy
    - geerlingguy.pip
    - usegalaxy-eu.supervisor
    - geerlingguy.nginx
    - galaxyproject.proftpd
    - usegalaxy-eu.certbot
  post_tasks:
    - name: Fix shed_tools path in shed_tool_conf.xml
      replace:
        path: "{{ galaxy_shed_tool_conf_file }}"
        regexp: '^<toolbox tool_path="../shed_tools">$'
        replace: '<toolbox tool_path="{{ galaxy_shed_tools_dir }}">'
      notify:
        - Restart Galaxy
