- name: Install and configure CVMFS references for Galaxy

  hosts: localhost
  vars:
      galaxy_config_location: /srv/galaxy/config
      home_location: "/home/{{ ansible_env.USER }}/"
      cvmfs_cache: /srv/cvmfs
      cvmfs_quota: "4000"

  tasks:

    - name: Create the cvmfs cache location
      file:
          path: "{{ cvmfs_cache }}"
          state: directory
      become: yes

    - name: Install some pre-requisites
      apt:
          name: lsb-release
          state: latest
      become: yes

    - name: Get the Cern apt repo.
      get_url:
          url: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
          dest: "{{ home_location }}/cvmfs-release-latest_all.deb"

    - name: Install the Cern repo
      apt:
          deb: "{{ home_location }}/cvmfs-release-latest_all.deb"
      become: yes

    - name: Delete the deb package
      file:
          path: "{{ home_location }}/cvmfs-release-latest_all.deb"
          state: absent

    - name: Install cvmfs client and config utility
      apt:
          update_cache: yes
          name: "{{ item }}"
          state: latest
      become: yes
      with_items:
          - cvmfs
          - cvmfs-config

    - name: Run the CVMFS config
      command: cvmfs_config setup
      become: yes

    - name: Create the default.local file
      template:
          src: default.local.js
          dest: /etc/cvmfs/default.local
      become: yes

    - name: Copy the repo and key files
      copy:
          src: "{{ item.file }}"
          dest: "/etc/cvmfs/{{ item.loc }}/{{ item.file }}"
      become: yes
      with_items:
          - { file: galaxyproject.org.conf, loc: domain.d }
          - { file: data.galaxyproject.org.pub, loc: keys }

    - name: Configure the Galaxy .yaml file.
      lineinfile:
          path: "{{ galaxy_config_location}}/galaxy.yml"
          regexp: '.*?tool_data_table_config_path:'
          line: "tool_data_table_config_path: /cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml,{{ galaxy_config_location }}/tool_data_table_conf.xml"
      become: yes
      become_user: galaxy

    - name: Restart Galaxy
      supervisorctl:
          name: "gx:"
          state: restarted
      become: yes
